"""Add cascade delete in webhook delivery model

Revision ID: 68fa8d4f0ba2
Revises: f160b9735f4b
Create Date: 2026-06-02 12:29:15.365196

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "68fa8d4f0ba2"
down_revision: Union[str, Sequence[str], None] = "f160b9735f4b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("webhook_deliveries_subscription_id_fkey"),
        "webhook_deliveries",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("webhook_deliveries_subscription_id_fkey"),
        "webhook_deliveries",
        "webhook_subscriptions",
        ["subscription_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("webhook_deliveries_subscription_id_fkey"),
        "webhook_deliveries",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("webhook_deliveries_subscription_id_fkey"),
        "webhook_deliveries",
        "webhook_subscriptions",
        ["subscription_id"],
        ["id"],
    )
    # ### end Alembic commands ###
